
deploy:
    script:
        - docker-compose -f ./compose_ci.yml build
        - docker-compose -f ./compose_ci.yml down
        - docker-compose -f ./compose_ci.yml up -d --force-recreate
    tags:
        - docker