insert into Challenge(title, topic, description, picture)
  values('10 Löffel sind ein Haus', 'Sammeln', 'Suche 10 Löffel und lege ein Haus.', 'https://live.staticflickr.com/5687/21676194079_71709b74ca_b.jpg'),
	('Tassenturm', 'Basteln', 'Stapele 5 Tassen, ohne das was kaputt geht.', 'https://publicdomainvectors.org/photos/StackOfCups.png'),
	('Kuschelberg', 'Sammeln', 'Wirf alle deine Kuscheltiere auf dein Bett.', 'https://live.staticflickr.com/2730/4164772348_440df70f2d_3k.jpg'),
	('Sammelwut', 'Sammeln', 'Sammel ein Gegenstand aus jedem Zimmer und lege sie auf den Küchentisch.', 'https://cdn.pixabay.com/photo/2019/12/15/12/32/things-4697014_1280.png'),
	('Lieblingsbücher', 'Sammeln', 'Finde deine liebsten 5 Bücher, stapele sie und stelle eine Topfpflanze drauf.', 'https://c2.peakpx.com/wallpaper/988/518/432/2k-book-bottle-still-life-vase-wallpaper-preview.jpg'),
	('Schuhschlange', 'Sammeln', 'Finde 3 rechte und 4 Linke Schuhe von allen Bewohnern und bauen eine Schuhschlange.', 'https://live.staticflickr.com/3425/3363658213_86b178864d_b.jpg'),
	('Kleidertausch', 'Basteln', 'Ziehe deinem liebsten Kuscheltier eine Hose & Pulli oder ein Kleid von dir an.', 'https://upload.wikimedia.org/wikipedia/commons/3/36/Cloths_of_Salem.jpg'),
	('Pack deine Tasche', 'Sammeln', 'Sammele 5 Gegenstände, die du brauchst wenn du in den Urlaub fährst.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Wriggle_House_-_Full-Grain_Genuine_leather_Holdall_Travel_Bag.jpg/1599px-Wriggle_House_-_Full-Grain_Genuine_leather_Holdall_Travel_Bag.jpg'),
	('Rot ist eine warme Farbe', 'Sammeln', 'Finde 5 rote Gegenstände aus deiner Wohnung und bilde ein großes Herz.', 'https://live.staticflickr.com/4101/34847480264_3a2f973285_5k.jpg'),
	('Gelb wie die Sonne', 'Sammeln', 'Finde gelbe Gegensstände und forme aus ihnen eine Leuchtende Sonne.', 'https://live.staticflickr.com/5138/5457677351_7b5b56fb6d_4k.jpg'),
	('Wohnungstour', 'Bewegung', 'Ein Auto, ein Fahrer und ein Ziel wo es hingehen soll.', ''),
	('Kunstliebhaber', 'Finden', 'Finde dein liebstes Bild bei dir zu hause, ein Bild an der Wand, ein Bild aus einem Buch oder ein Blick durch den Raum und fotografiere es.', 'https://live.staticflickr.com/7546/16333989232_b2d2ea838c_h.jpg'),
	('Lunch for you', 'Sammeln', 'Sammele alle Lebensmittel ein, die du benötigst um dein Mittagessen zuzubereiten.', 'https://live.staticflickr.com/1853/42838746640_aa3a23d8b1_3k.jpg'),
	('Küchenhelfer', 'Sammeln', 'Finde deine 3 wichtigsten Küchenhelfer.', 'https://live.staticflickr.com/65535/40745486313_b8b9950853_6k.jpg'),
	('Techalarm', 'Sammeln', 'Sammele alle Tastaturen, Tablets und Smartphones die ihr im Haus habt und baut euch ein Techteppich.', 'https://live.staticflickr.com/105/299512707_83e315c420_b.jpg'),
	('Werd zum Maler', 'Kochen', 'Koche dein Lieblingsessen und male ein Bild davon ohne mit der Hand abzusetzen.', 'https://cdn.pixabay.com/photo/2012/04/13/11/24/loaf-31957_1280.png'),
	('Macht Musik', 'Musizieren', 'Suche dir 2 Gegenstände mit denen du Musik machen kannst (Topfdeckel sind auch erlaubt). Nimm ein Lied auf.', 'https://live.staticflickr.com/3301/3552356162_a41a9faa28_k.jpg'),
	('ZweitesIch', 'Basteln', 'Suche dein Lieblingsoutfit zusammen und präpariere zummen mit etwas rundem, das deinen Kopf nachahmen soll, auf dem Boden.', ''),
	('Stiftechaos', 'Basteln', 'Sortiere deine Stifte nach Farben und mach ein Foto.', 'https://p2.piqsels.com/preview/1013/356/961/color-colored-colorful-colors.jpg'),
	('Bunte Wände, buntes Leben, gute Laune', 'Basteln', 'Finde die bunteste Wand bei dir und lege 3 bunte Kissen davor.', 'https://cdn.pixabay.com/photo/2012/03/04/00/04/colorful-21747_1280.jpg'),
	('Baue deinen Superheld!', 'Basteln', 'Finde 6 Gegenstände und lege sie so zusammen, das sie aussehen wie ein Superheld. Welchen darfst du dir aussuchen.', ''),
	('Lustig wie nie zuvor!', 'Schreiben', 'Falte ein A4 Blatt 4 mal und schreibe ein Witz drauf.', ''),
	('Der schiefe Turm von Stuhlhausen', 'Basteln', 'Sammele 5 Stühle und stapele sie übereinander.', 'https://cdn.pixabay.com/photo/2016/10/06/03/03/chairs-1718067_1280.jpg'),
	('Origami', 'Basteln', 'Such dir ein Stück Papier und falte einen Origamivogel.', 'https://get.pxhere.com/photo/animal-art-background-bird-bright-card-close-up-colorful-creativity-cute-decoration-decorative-design-folded-handicraft-handmade-isolated-lay-flat-letter-micro-object-origami-paper-paper-craft-top-view-toy-white-wing-art-paper-origami-paper-craft-1438957.jpg?__cf_chl_jschl_tk__=8576036f9b3bd274f97b8e28f22f5c40234c0c83-1584796601-0-AUinRRJHpRrqHyEH860iLIWGOVM8SXszX49uzdxUStVPaANpDVpAYwJslGuo4lrXAPHZ78jbKjhMEAdT48mIl1vrWcrk1sOjt06ThDqBkIhnpzatzcDf3N4Lp1VPxc8-aTc_R9WvPt6qzdKpCD9lJ-JjU3uJ76IfrdApPQlLhLBeOQgAENx1chSjRYID4ZErB9Z8xeLBxQ_V41hxiDJ2dV6_OlRO9FTKg2hZfEoJRGPQJswCXTEkV3faSJPto3QjJknqBCt7WnCp3CK6zsT_VQrH4QOSJzPlhwd6ti55mPd_dPkWfa2VducIEvCAlqQGqb09ZwETkQVPVZjyIHuv8CPuKW53Hw_aYWZK4DfTUG8NoCYkZ398FO20shepXbR7Ihcoar8mikqyomVvLtpaTCJaRS62fvyFdGx_SEmK7rF8gOMc5TiLgQo2URO23tkSkDxlT-N0wNoy51Q_GY4d50Bey6bYCDEpSKURfKWpkJyqN1zzInC7vOg9adWt82WirZlVN02IKDc65Z3j1rTZ-YXKnOjhdXW1JeG64p8W0Q2s_TKSr2hfAI2rTlKYLvUrt5ujcTbadC9e4XmFaXMNTSwbQAU5KLAiers72HuYL7RK'),
	('Höhlenbau', 'Basteln', 'Baut euch eine Höhle unter dem Couchtisch und zieht dort ein Weile ein.', ''),
	('Puzzle', 'Spielen', 'Such dir ein Puzzle und löse es.', 'https://pixnio.com/free-images/2017/05/23/2017-05-23-17-39-09-900x600.jpg'),
	('Klopapier', 'Basteln', 'Sammle leere Klopapierrollen und bastele etwas draus.', 'https://upload.wikimedia.org/wikipedia/commons/1/1c/No_toilet_paper.jpg'),
	('Saubermann', 'Aufräumen', 'Finde das Zimmer mit der größten Unordnung und räume es auf.', 'https://cdn.pixabay.com/photo/2017/05/07/18/59/office-2293223_1280.jpg'),
	('Amtsschimmel', 'Sammeln', 'Sammle Belege für Deine nächste Steuererklärung - jetzt ist Saison.', 'https://foto.wuestenigel.com/wp-content/uploads/api/finanzamt-steuererklarung-ausfullen.jpeg'),
	('Sockenmemory', 'Finden', 'Nimm alle Socken auseinander und lege sie in eine Schublade. Wer findet die meisten Paare?', ''),
	('WasDerKühlschrankhergibt', 'Kochen', 'Erstelle ein Inventar Deines Kühlschranks und plane einen Kochplan für die nächste Woche.', 'https://cdn.pixabay.com/photo/2018/06/15/01/18/fridge-3475996_1280.jpg'),
	('Auf dem Kopf', 'Finden', 'Gestalte ein Foto so, als ob die Wohnung auf dem Kopf steht', 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Bispingen_verr%C3%BCcktes_Haus_auf_dem_Kopf.jpg'),
	('Chaos-Schublade', 'Aufräumen', 'Jeder hat diese eine Schublade, in der alles rumfliegt. Räum sie auf!', ''),
	('Ohne Pinsel ', 'Malen', 'Male ein Bild  mit deiner Nase. Mache ein Selfie von dir und dem fertigen Bild.', ''),
	('Dein Ausblick', 'Malen', 'Male was du aus deinem Fenster siehst.', ''),
	('Alles neu', 'Lernen', 'Lerne etwas neues (Häkeln, Handstand, Origami, ein neues Rezept, etc.) Mach ein Foto von deinem ersten Versuch und deinem letzten Versuch.', 'https://pixnio.com/free-images/2017/05/23/2017-05-23-16-16-50-900x596.jpg'),
	('Social Fun', 'Finden', 'Finde ein lustiges Video und schicke es deiner besten Freundin/ deinem besten Freund.', 'https://publicdomainvectors.org/photos/MobilePhone_remix.png'),
	('Entschleunigung', 'Bewegung', 'Laufe so langsam es geht, durch dein Wohnzimmer.', 'https://cdn.pixabay.com/photo/2016/07/09/15/27/snail-1506393_1280.jpg'),
	('Bilderchallenge', 'Finden', 'Mache ein Bild von deinem Schreibtischstuhl.', 'https://get.pxhere.com/photo/person-creative-music-people-girl-woman-camera-photography-photographer-female-red-lens-equipment-color-child-professional-profession-lady-taking-picture-outdoors-fun-singing-photograph-shoot-beauty-shot-photographing-snap-hobby-woman-photographer-559569.jpg?__cf_chl_jschl_tk__=3700019e0a67c1077434f30933aef43ff90049dd-1584799722-0-AbyA2Nc7Wmin-fc99UHX_nlKAuukKkjyy0_Bbe0X2qUonU55jmCD4Bxv3ZbJSHbxOJrff0NofkEbZzRT75vIrTKvkJRFeeMpUfdmp5FdF3k4lp1-Sl49jQm4ABNmxtanGtrah2Z4EZUhrK_jDa8HyxCYwY3XybOgF-PCWyhWVZx2YJaxv2DTsGv-U-ZucTETIspi8jsAX2K8zsQN7vGZvJ78vtrSfX3Wpnrhc8ntfgsT9ayUP1lCIvz7xwaRWT62D9utry189bywqMC55Qy6O4hzF40LxDm5hKhmgBGTgXTdr7fdZDtw8g0XI5niE26h6E2CLUXn6vf0-Us81h4BfGmYuyLXpZpTYIOgmlywHxtE2uWPmlQsQtIKBN3q5Qw4VV_E_laMHDOK-_KFdPGxFSjmSNImfAIyqTiROKw-a8ueMYw6uwutkrflwaNzwELlLWq6NNjGB7cjhn0bmVXld3Dw5xbxbRS5-ZJZFSt7V96x1xr6g97FX58ju-DQId8LJg0BwmunCOLF9kn43pTuKUl8ObqVXLamnjNTDRogVDU0sleNHAfWeRyx7uBreYsHhatsV_iq1v3P3XgF0jwQiCmMV3jXw_hg89nd2Yts-4eL'),
	('Die Pyramiden von Klo-patra', 'Basteln', 'Baue zwei Klopapier Pyramiden.', ''),
	('Gedicht - thcideg', 'Schreiben', 'Schreibe ein Gedicht, Minimum 10 Zeilen - aber rückwärts! Lies es vor', ''),
	('Brieffreunde', 'Schreiben', 'Schreibe einen Brief oder eine Postkarte an deine Oma, deinen Opa, ...', ''),
	('Es war einmal ...', 'Basteln', 'Gestalte mit Gegenständen aus deiner Wohnung ein Foto, das ein Märchen darstellt.', ''),
	('Let''s Dance', 'Bewegung', 'Du hast doch bestimmt ein Lieblingslied! Tanz dazu.', ''),
	('Virtueller Sport', 'Bewegung', 'Finde eine Sportgruppe oder Videochatte mit deinen Freunden und macht gemeinsam Sport.', 'https://cdn.pixabay.com/photo/2017/05/26/20/18/marathon-2346948_1280.jpg'),
	('Hände waschen', 'Video', 'Mache ein (lustiges) Video, wie du dir die Hände wäscht und du sagst, warum das wichtig ist.', 'https://live.staticflickr.com/8159/6963932022_8a243ccb35_k.jpg'),
	('Kochchallenge', 'Kochen', 'Koche etwas mit nur drei Zutaten (Gewürze ausgenommen).', 'https://live.staticflickr.com/1915/44909179814_44123cb4ce_6k.jpg'),
	('Applaus', 'Bewegung', 'Stell dich an dein Fenster und applaudiere den Helferinnen und Helfern.', ''),
	('Der Boden ist Lava', 'Bewegung', 'Schaffst du es, dich eine Stunde lang durch die Wohnung zu bewegen ohne den Boden zu berühren?', ''),
	('Mottotag: Kindheitshelden', 'Foto', 'Verkleide dich als einer deiner Kindheitshelden.', 'https://cdn.pixabay.com/photo/2017/07/06/18/48/wonder-woman-2478971_1280.jpg'),
	('Mottotag: Verkehrt-Herum', 'Foto', 'Heute ist alles verkehrt herum. Eure Kleidung, euer Essen (startet doch mal mit dem Dessert), ...', 'https://cdn.pixabay.com/photo/2016/10/14/17/54/sloth-1740761_1280.jpg'),
	('Tutorial-Tag', 'Lernen', 'Schau dir ein Tutorial an und lerne die gezeigte Fähigkeit.', 'https://cdn.pixabay.com/photo/2018/08/11/11/34/training-3598457_1280.jpg'),
	('Der nächste Bestseller', 'Schreiben', 'Stell dich an dein Fenster und applaudiere den Helferinnen und Helfern.Schreibe eine Geschichte mit dir in der Hauptrolle.', ''),
	('Satzmixer', 'Schreiben', 'Schlage mehrere Bücher auf und schreibe jeweils den ersten Satz auf ein Papier, bis du eine ganze Seite voll hast.', 'https://cdn.pixabay.com/photo/2018/07/01/20/01/book-3510326_1280.jpg'),
	('Collagenkünstler', 'Basteln', 'Sammle Zeitungen, Werbeprospekte und Ähnliches, schneide einzelne Teile aus und lege oder klebe eine Collage.', 'https://cdn.pixabay.com/photo/2014/11/07/16/19/vision-board-520757_1280.jpg'),
	('Deep Cleaning', 'Aufräumen', 'Diese eine Stelle unterm Sofa, hinterm Kühlschrank oder ganz oben auf dem Schrank wurde das letzte Mal beim Einzug geputzt. Mach dort sauber.', ''),
	('Heute ist ein guter Tag', 'Schreiben', 'Schreibe mindestens drei Dinge auf, die heute gut waren.', 'https://cdn.pixabay.com/photo/2017/08/03/11/28/ferris-wheel-2575709_1280.jpg'),
	('Schranktastic', 'Basteln', 'Sortiere deine Hemden/Blusen nach deren Farben.', ''),
	('Bowling', 'Bewegung', 'Nehmt eure Pfandflaschen und einen kleinen Ball (Tennisball/Massageball/...) und baut eure eigene Kegelbahn', ''),
	('Upcycling', 'Basteln', 'Nehmt gebrauchte Dosen, Flaschen, Stoffe, Tüten und verarbeitet diese zu tollen neuen Sachen.', ''),
	('Tischtennis', 'Bewegung', 'Nehmt einen Tischtennisball und spielt auf dem Esszimmertisch.', ''),
	('Kissenschlacht', 'Bewegung', 'Macht eine Kissenschlacht.', '');
